### ISSUE TITLE
Accessing Huge files/Lots of files in the CNPC Playerdata freezes / crashes server

### ISSUE THREAD

**Issue by Eisenbahn** [KAMKEEL/CustomNPC-Plus#7]
Opening huge playerdata quest json freezes server for a while.

Basically server's hangs for a while if a player with, lets say, 155kb+ of data JOINS server.
We have some servers where we use a lot of Customnpcs, there are lots of quests, dialogs and (not anymore, we learn that's not a good idea specially because of the file's size) item-givers npcs.

This is perfectly fine on 1.12, i believe its because of the Buffer thing.

Also, the buffer thing fixes some critical issues, like crashing the server if you try opening your playerdata thru your npc wand and it has lots of files or try to set/read/complete dialog/quest thru noppes command and has lots of files... Let's say 4000+ files you can already see what i'm talking about...

* Minecraft: 1.7.10
* Forge 10.13.4.1614: 
* CustomNPCs_1.7.10d(29oct17):

**Comment by KAMKEEL** [comment]
I'll take a look. But this is the thread for CustomNPC Plus and you are still using regular CustomNPCs But, I hope I can address this issue since it was in the original.

**Comment by Eisenbahn** [comment]
Thanks! You are doing a great job here with CNPC <3

**Comment by luiz-otavio** [comment]
I did some lookup inside CustomNPC and I think `IExtendedEntityProperties` should be a good choice to storing/writing massive data instead of JSON. Besides of `IExtendedEntityProperties` there's a lot of compression and methods for reading which is better.

By the way, it's not a good case to make your own json codec. You should use popular libraries like Gson or Jackson to do something like that. 

If you want, I could make a fork of this project and then make it on with `IExtendedEntityProperties`.

**Comment by KAMKEEL** [comment]
Hey Everyone,
Until further notice, I will not be working on this issue. As it may break many servers that already pre-exist. However, @c0508383 and I will take a look to see if we can _minimize_ file data. However, we do not want to break upgrading versions.

**Comment by KAMKEEL** [comment]
@Eisenbahn V1.5.2 was just released with **ZSTD** compression. With this new compression, it should solve some disk issues that you may be having on your server. Please read the whole changelog for 1.5.2 and back up ALL CNPC+ data.

[V1.5.2](https://github.com/KAMKEEL/CustomNPC-Plus/releases/tag/1.5.2 )
